name: flutter_html_editor_forked
description: HTML rich text editor for Android, iOS, and Web, using the Summernote library.
  Enhanced with highly customizable widget-based controls, bug fixes, callbacks, dark mode, and more.
version: 0.0.1
homepage: https://github.com/amirr-dotcom/flutter_html_editor_forked

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_inappwebview: ^5.4.3+7
  flutter_keyboard_visibility: ^5.2.0
  visibility_detector: ^0.3.3
  file_picker: ^4.5.1
  pointer_interceptor: ^0.9.3+1
  flex_color_picker: ^2.5.0
  numberpicker: ^2.1.1
  meta: '>=1.0.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.devnation.flutter_html_editor_forked
        pluginClass: FlutterHtmlEditorForkedPlugin
      ios:
        pluginClass: FlutterHtmlEditorForkedPlugin
      web:
        pluginClass: FlutterHtmlEditorForkedWeb
        fileName: flutter_html_editor_forked_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/flutter_html_editor_forked/summernote.html
    - packages/flutter_html_editor_forked/summernote-no-plugins.html
    - packages/flutter_html_editor_forked/summernote-lite.min.css
    - packages/flutter_html_editor_forked/summernote-lite-dark.css
    - packages/flutter_html_editor_forked/summernote-lite.min.js
    - packages/flutter_html_editor_forked/jquery.min.js
    - packages/flutter_html_editor_forked/assets/font/summernote.eot
    - packages/flutter_html_editor_forked/assets/font/summernote.ttf
    - packages/flutter_html_editor_forked/assets/font/summernote.woff
    - packages/flutter_html_editor_forked/assets/font/summernote.woff2
    - packages/flutter_html_editor_forked/assets/plugins/summernote-at-mention/summernote-at-mention.js
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
