name: flutter_html_editor_forked
description: HTML rich text editor for Android, iOS, and Web, using the Summernote library.
  Enhanced with highly customizable widget-based controls, bug fixes, callbacks, dark mode, and more.
version: 0.0.1
homepage: https://github.com/amirr-dotcom/flutter_html_editor_forked

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  flutter_inappwebview: ^5.7.2+3
  flutter_keyboard_visibility: ^5.4.1
  visibility_detector: ^0.4.0+2
  file_picker: ^5.3.1
  pointer_interceptor: ^0.9.3+4
  flex_color_picker: ^3.2.2
  numberpicker: ^2.1.2
  meta: '>=1.0.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  # plugin:
  #   platforms:
  #     android:
  #       package: com.devnation.flutter_html_editor_forked
  #       pluginClass: FlutterHtmlEditorForkedPlugin
  #     ios:
  #       pluginClass: FlutterHtmlEditorForkedPlugin
  #     web:
  #       pluginClass: FlutterHtmlEditorForkedWeb
  #       fileName: flutter_html_editor_forked_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/flutter_html_editor_forked/assets/summernote.html
    - packages/flutter_html_editor_forked/assets/summernote-no-plugins.html
    - packages/flutter_html_editor_forked/assets/summernote-lite.min.css
    - packages/flutter_html_editor_forked/assets/summernote-lite-dark.css
    - packages/flutter_html_editor_forked/assets/summernote-lite.min.js
    - packages/flutter_html_editor_forked/assets/jquery.min.js
    - packages/flutter_html_editor_forked/assets/font/summernote.eot
    - packages/flutter_html_editor_forked/assets/font/summernote.ttf
    - packages/flutter_html_editor_forked/assets/font/summernote.woff
    - packages/flutter_html_editor_forked/assets/font/summernote.woff2
    - packages/flutter_html_editor_forked/assets/plugins/summernote-at-mention/summernote-at-mention.js 